### ISSUE TITLE
Help: Fix to your issue to fastpages blog!

### ISSUE THREAD

**Issue by marcelcaraciolo** [sebderhy/impactfulai#2]
Hello @sebderhy , I saw your post about the issue related to fastpages blog issue. I faced the same issue as you, but I didn't have time to migrate to the proposed solution: quarto.org

I discovered the issue and made my blog build again. The problem is the remote theme used:  minima.

What I did was to point the remote theme to a previous commit . I believe the main branch now  is bringing issues to the older fastpages branch .

Here's my patch that you can also perform at yours (the file is the _config.yml):

https://github.com/sebderhy/impactfulai/blob/7f69ab543636990926d609af47629011ca447757/_config.yml#L103

[https://github.com/corriporai/pandasrunner/blob/26cf5cbc0b027bf4761cfc7e3abc8a9a867eec85/_config.yml#L103](https://github.com/corriporai/pandasrunner/blob/26cf5cbc0b027bf4761cfc7e3abc8a9a867eec85/_config.yml#L103
)

After that everything went great and I could build and deploy my blog again.

https://corriporai.github.io/pandasrunner/general/jupyter/releases/2022/12/29/release-v060.html

**Comment by sebderhy** [comment]
Hey @marcelcaraciolo thanks a lot for the tip, it worked perfectly!!

**Comment by litkm** [comment]
@sebderhy I saw your comment [here](https://forums.fast.ai/t/fastpages-deprecating-fastpages-in-favor-of-quarto/99095). Thank for you for posting it and then updating it.

And, @marcelcaraciolo thank you very much for providing this fix!! I have also used it and can build my blog again. Much appreciated.
